INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (1,13,47,68,'gravida mauris','Donec',4694);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (2,98,4,22,'nec ante','tempor bibendum. Donec felis orci,',4742);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (3,71,39,23,'libero at','risus.',454);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (4,65,54,7,'Cras vehicula','facilisis lorem tristique aliquet. Phasellus',1913);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (5,97,53,56,'vel, venenatis','non, feugiat nec, diam. Duis',3551);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (6,80,65,79,'Integer aliquam','Mauris vestibulum, neque sed',23);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (7,85,27,49,'orci sem','Vestibulum',4786);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (8,74,42,46,'mauris id','ac orci. Ut',2618);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (9,25,42,8,'rhoncus. Proin','quis diam luctus lobortis. Class',3415);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (10,35,81,96,'non, lobortis','gravida',4321);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (11,10,23,83,'consequat nec,','feugiat tellus',2764);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (12,84,1,73,'Aliquam fringilla','orci,',92);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (13,81,44,27,'enim. Curabitur','Nam consequat dolor vitae dolor.',2651);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (14,99,81,83,'Nullam scelerisque','erat. Sed nunc est, mollis',1874);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (15,13,49,21,'dui, in','lobortis ultrices. Vivamus rhoncus.',3330);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (16,44,43,96,'quis, pede.','odio. Aliquam vulputate',2449);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (17,51,15,93,'nulla. Cras','est ac facilisis',4883);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (18,4,27,100,'Donec est.','et ipsum',3474);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (19,12,20,99,'tristique ac,','libero. Proin mi. Aliquam gravida',5470);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (20,23,29,56,'nec quam.','sodales at,',1831);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (21,70,68,77,'Phasellus libero','et,',2214);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (22,70,5,52,'ut aliquam','scelerisque neque. Nullam',1917);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (23,25,83,71,'orci luctus','lacus pede sagittis augue,',4129);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (24,84,28,97,'molestie arcu.','tortor at risus. Nunc ac',4747);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (25,46,39,24,'amet nulla.','Pellentesque',5657);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (26,62,100,100,'neque. Nullam','ligula elit, pretium et,',4452);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (27,43,47,80,'Vivamus nisi.','dictum eu, eleifend nec,',5272);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (28,85,29,82,'ridiculus mus.','pharetra, felis eget varius',1966);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (29,42,57,14,'blandit mattis.','bibendum sed, est.',4446);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (30,84,82,86,'Aliquam fringilla','Nulla',4419);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (31,68,39,33,'Nunc commodo','a nunc.',2978);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (32,54,91,60,'Nullam enim.','eleifend, nunc risus varius orci,',2181);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (33,95,57,55,'Aliquam nec','sollicitudin a,',622);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (34,6,75,32,'nascetur ridiculus','placerat, orci lacus vestibulum',1163);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (35,26,23,69,'vulputate, nisi','interdum. Sed auctor',14);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (36,93,23,64,'Quisque fringilla','Suspendisse eleifend. Cras sed leo.',5499);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (37,78,43,11,'cursus vestibulum.','morbi tristique senectus et netus',5551);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (38,65,9,98,'non, egestas','erat.',3745);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (39,10,20,86,'arcu ac','montes,',3262);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (40,28,100,81,'sagittis semper.','risus, at',1173);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (41,25,80,49,'quis, pede.','Ut tincidunt vehicula risus. Nulla',4346);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (42,27,90,32,'ullamcorper, velit','mollis. Phasellus libero',212);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (43,14,8,81,'Donec sollicitudin','tempor augue ac ipsum.',2831);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (44,60,83,42,'porta elit,','turpis nec mauris blandit mattis.',2831);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (45,63,29,57,'purus gravida','a',568);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (46,83,83,68,'risus. In','justo faucibus lectus, a',3090);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (47,7,23,68,'mi felis,','Sed pharetra, felis eget varius',3189);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (48,67,92,12,'eu tellus','ac turpis egestas.',4563);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (49,12,9,82,'sed dictum','torquent per',5274);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (50,64,21,16,'elit. Etiam','netus et malesuada',1132);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (51,32,70,87,'ac libero','velit. Quisque varius. Nam',4874);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (52,90,13,42,'gravida sit','ac turpis egestas. Fusce',4031);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (53,60,84,46,'dui, in','et, commodo at,',5180);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (54,26,93,81,'Nunc mauris','est. Nunc laoreet lectus',3916);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (55,89,56,62,'est ac','non, feugiat nec, diam. Duis',801);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (56,39,13,67,'sociis natoque','felis purus ac',3054);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (57,20,79,73,'facilisis, magna','enim mi tempor lorem, eget',1788);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (58,20,69,57,'augue ut','vitae nibh. Donec',2390);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (59,43,68,39,'Curabitur ut','Lorem ipsum dolor',3673);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (60,95,9,77,'sagittis. Nullam','Sed malesuada augue ut',2055);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (61,76,12,88,'Nulla tincidunt,','Phasellus nulla. Integer vulputate, risus',1201);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (62,90,23,14,'molestie pharetra','felis.',5434);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (63,99,39,47,'volutpat. Nulla','nec',3417);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (64,71,64,57,'vel nisl.','sed dictum eleifend, nunc risus',370);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (65,17,8,26,'Nunc pulvinar','Nunc pulvinar',4365);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (66,35,42,45,'nonummy ut,','magna.',3200);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (67,51,54,34,'pede nec','leo elementum',3748);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (68,25,58,55,'turpis non','Donec',3909);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (69,51,89,73,'velit. Quisque','eget',40);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (70,60,46,63,'scelerisque, lorem','lacus. Quisque imperdiet, erat',4313);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (71,2,7,81,'elit. Etiam','tincidunt',4721);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (72,19,8,60,'lacus. Cras','pede.',3284);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (73,75,14,71,'eget nisi','lobortis,',3396);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (74,54,72,24,'nulla. Integer','parturient',2319);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (75,16,83,87,'Ut semper','augue. Sed molestie. Sed id',5395);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (76,26,18,2,'dolor quam,','pede, ultrices a, auctor',3593);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (77,41,99,84,'arcu ac','Aenean euismod',1990);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (78,31,58,41,'eleifend. Cras','id, mollis nec, cursus',4984);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (79,14,77,1,'malesuada ut,','aliquet nec,',2359);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (80,51,52,49,'urna, nec','mauris eu elit. Nulla facilisi.',1221);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (81,86,58,10,'Donec non','imperdiet dictum magna. Ut',905);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (82,9,5,29,'elementum purus,','ut,',3534);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (83,34,16,100,'nascetur ridiculus','diam. Duis mi',3208);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (84,62,33,15,'eu elit.','dignissim tempor arcu. Vestibulum',2255);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (85,65,55,77,'turpis non','rutrum,',332);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (86,52,48,38,'semper erat,','pulvinar arcu et',2004);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (87,75,53,20,'ac turpis','gravida sit amet, dapibus id,',2357);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (88,75,100,92,'semper, dui','ante. Vivamus non',2769);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (89,89,73,51,'Suspendisse eleifend.','risus',198);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (90,79,55,33,'malesuada fames','non, cursus non,',5889);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (91,85,32,94,'lorem eu','Morbi accumsan',4473);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (92,49,4,29,'est, congue','magna.',3126);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (93,43,69,65,'aliquet. Phasellus','consectetuer adipiscing elit.',1987);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (94,1,37,47,'justo faucibus','ac',3862);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (95,88,10,98,'litora torquent','tincidunt pede ac',2527);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (96,89,84,74,'amet luctus','erat,',5514);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (97,4,69,27,'nec ligula','Donec',264);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (98,25,2,74,'ac turpis','Integer urna. Vivamus molestie',5832);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (99,22,85,87,'convallis est,','nec, malesuada ut,',1089);
INSERT INTO PRODUCT (id_product,id_supplier,id_product_type,id_unit,product_name,description,price) VALUES (100,74,64,22,'tellus eu','gravida.',4913);
