INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (1,'Sodales Inc.','amet lorem semper auctor. Mauris');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (2,'Nibh Lacinia Orci Foundation','enim. Nunc ut erat. Sed nunc est, mollis non,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (3,'Magna Tellus Ltd','quam. Pellentesque habitant');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (4,'Parturient Foundation','euismod est arcu ac orci.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (5,'Mauris Corporation','tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (6,'Duis Gravida Praesent Limited','eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (7,'Amet Consectetuer Adipiscing Corp.','risus varius orci, in consequat enim diam vel arcu.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (8,'Convallis Erat Corp.','facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (9,'Et Institute','facilisis, magna');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (10,'Quisque Fringilla Corporation','nisl. Nulla eu neque pellentesque massa lobortis ultrices.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (11,'Aliquam Foundation','dolor, nonummy ac, feugiat non, lobortis');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (12,'Gravida Aliquam Tincidunt Limited','posuere at, velit. Cras lorem lorem,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (13,'Rutrum Justo Praesent LLC','vulputate');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (14,'Diam Inc.','enim. Sed nulla ante, iaculis nec, eleifend non,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (15,'Dolor Ltd','mauris blandit mattis.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (16,'Eu Turpis LLP','lacus. Quisque imperdiet,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (17,'Amet Corporation','in sodales elit');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (18,'Curabitur Corp.','imperdiet dictum magna.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (19,'Metus Industries','nunc sit amet metus.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (20,'Quisque Nonummy Limited','risus, at');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (21,'Lobortis Tellus Justo Foundation','ut erat. Sed');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (22,'Quis LLC','quis arcu vel quam dignissim pharetra. Nam');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (23,'Duis Ltd','pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (24,'Ipsum Nunc Id PC','ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (25,'Laoreet Limited','Donec at arcu.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (26,'Semper Auctor Mauris Consulting','vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (27,'Tincidunt Vehicula Risus PC','diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (28,'Eleifend Associates','purus mauris a nunc. In at');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (29,'Vulputate Associates','est ac facilisis');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (30,'Semper PC','lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (31,'Habitant Morbi LLC','Curabitur egestas nunc sed libero.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (32,'Aliquam Adipiscing Lacus PC','Quisque ornare tortor at');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (33,'Justo Proin Non Corporation','mi lacinia mattis. Integer eu');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (34,'Non Vestibulum Nec Corporation','Integer id magna et ipsum cursus');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (35,'Ullamcorper Duis At Consulting','Donec tempor, est ac mattis semper, dui lectus rutrum');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (36,'Ac Urna Ut Inc.','lectus ante dictum mi, ac mattis velit justo nec ante.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (37,'Id Risus Company','magna. Duis');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (38,'Quam Quis Diam Associates','convallis in, cursus et, eros. Proin ultrices. Duis');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (39,'In Consectetuer Consulting','ut, pharetra sed, hendrerit a,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (40,'Mauris Incorporated','imperdiet, erat nonummy ultricies ornare, elit elit fermentum');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (41,'Nunc Consulting','habitant');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (42,'Massa Corp.','cursus luctus, ipsum leo elementum sem, vitae');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (43,'Rutrum Fusce Dolor Incorporated','amet luctus');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (44,'Et Euismod Et Consulting','quam a');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (45,'Urna LLC','purus gravida sagittis. Duis gravida.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (46,'Tempor Lorem Eget Industries','consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (47,'Rhoncus Id Company','Integer vulputate, risus a ultricies adipiscing,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (48,'Nunc Sollicitudin Commodo Corp.','commodo auctor velit. Aliquam nisl. Nulla eu neque');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (49,'Tristique Senectus Corp.','vitae dolor. Donec fringilla. Donec feugiat');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (50,'Mi Enim Condimentum Industries','Nulla');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (51,'Suspendisse Commodo PC','eget massa. Suspendisse eleifend. Cras sed leo. Cras');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (52,'Inceptos Hymenaeos Limited','ac ipsum.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (53,'Mi Aliquam Gravida Consulting','sit amet, risus. Donec nibh enim, gravida');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (54,'Ut Associates','Nam interdum enim non nisi. Aenean eget');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (55,'Nascetur Ridiculus Mus Company','nunc ac mattis ornare, lectus ante');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (56,'Condimentum Eget Volutpat Corporation','vel nisl. Quisque fringilla');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (57,'Nec Luctus Felis Institute','aliquet, metus urna convallis erat, eget tincidunt dui augue eu');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (58,'Metus Eu Erat Foundation','interdum libero dui nec');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (59,'Massa Vestibulum Industries','Mauris ut quam vel sapien imperdiet');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (60,'Et Risus Inc.','pellentesque');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (61,'Dignissim LLP','eu nibh vulputate');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (62,'Neque Sed Dictum Associates','Duis a mi fringilla mi lacinia');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (63,'Dui Fusce Institute','libero et tristique pellentesque, tellus sem mollis dui, in sodales');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (64,'Nulla Facilisi Industries','ipsum non arcu. Vivamus sit amet');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (65,'Dignissim Lacus Corp.','commodo hendrerit. Donec porttitor tellus non magna. Nam');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (66,'Augue Ac LLC','vel arcu. Curabitur ut odio vel est');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (67,'Enim Etiam Gravida Foundation','nisl. Maecenas malesuada');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (68,'Lectus Consulting','nunc. In at pede. Cras vulputate velit');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (69,'Egestas Hendrerit Neque Industries','eu');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (70,'Vel Corp.','eu elit. Nulla facilisi.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (71,'Vestibulum Neque Ltd','Nulla semper tellus id nunc interdum feugiat.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (72,'Fringilla Purus Industries','posuere cubilia Curae; Donec tincidunt. Donec');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (73,'Pretium Aliquet Inc.','mauris sagittis placerat.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (74,'Nec Tempus Company','id,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (75,'Ornare Foundation','Lorem ipsum dolor sit amet,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (76,'Sapien Cras Dolor Limited','mauris.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (77,'Orci Ut Sagittis LLC','non, hendrerit id, ante. Nunc');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (78,'Nam Industries','eleifend, nunc risus varius orci, in consequat');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (79,'Purus Nullam Scelerisque LLC','quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (80,'Enim Ltd','accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (81,'Placerat Velit Quisque Institute','a, magna.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (82,'Et Company','nonummy ipsum non arcu. Vivamus sit amet risus.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (83,'Pellentesque Incorporated','ultricies adipiscing, enim');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (84,'Mauris Inc.','varius ultrices, mauris ipsum porta elit, a');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (85,'Mattis Consulting','mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (86,'Semper LLC','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (87,'Duis Ac Associates','nec, diam. Duis mi enim, condimentum eget,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (88,'Lectus Institute','varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (89,'Molestie Sed LLC','amet ornare lectus justo eu arcu. Morbi sit');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (90,'Scelerisque Neque Limited','arcu. Vestibulum ante ipsum primis in faucibus');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (91,'Non Quam Corp.','adipiscing lobortis risus. In mi pede, nonummy ut,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (92,'Molestie Corp.','eget odio. Aliquam vulputate ullamcorper');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (93,'Molestie Sed Id Incorporated','lectus. Nullam suscipit, est ac');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (94,'Donec Industries','erat nonummy ultricies ornare, elit');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (95,'Eu LLP','consectetuer adipiscing elit. Etiam laoreet, libero et tristique');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (96,'Libero Lacus Corp.','In mi pede, nonummy');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (97,'Mauris Vestibulum Neque Industries','vel est');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (98,'Mi Consulting','Sed nunc est, mollis non,');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (99,'At Fringilla Corporation','ac urna. Ut');
INSERT INTO SUPPLIER (id_supplier,supplier_name,supplier_info) VALUES (100,'Hendrerit Donec Porttitor Incorporated','dolor. Quisque tincidunt pede ac urna. Ut');
